### ISSUE TITLE
Support CR profile

### ISSUE THREAD

**Issue by tripu** [w3c/echidna#522]
High-level meta-issue to keep track of tasks involved:

* [ ] #523 (automate approval of CR requests by the project manager):
Echidna API / Echidna web UI / **GH issues** ⬅️ / some other approach.
* [ ] How to send the CfE:
**Do from new IPP Symfony code** ⬅️ / do in script / do from Echidna / &hellip;
* [ ] #524 Give submitters a mechanism to indicate whether changes are purely editorial, or substantive:
There will be a new parameter for that.
* [ ] w3c/specberus#39 (improve detection of preliminary implementation/interoperability reports).
* [ ] Detect if it's a CR coming from an edited REC (in such case the *shortlink* does not change; see diagram below).

![diagram](https://w3c.github.io/tr-pages/deprecation.svg)

**Comment by deniak** [comment]
Workflow agreed with Directors and Comm
![echidna-cr](https://user-images.githubusercontent.com/1696128/41649309-60ba764c-748c-11e8-9ad8-767ae0ae7f18.jpg)
